# Ruff configuration for pybibx
# See https://beta.ruff.rs/docs/configuration/

# Same as Black.
line-length = 88
indent-width = 4

# Assume Python 3.10 compatibility.
target-version = "py310"

# Enable Pyflakes `F` and Pycodestyle `E` and `W` codes by default.
# `D` for pydocstyle
# `I` for isort
# `B` for flake8-bugbear
# `C4` for flake8-comprehensions
# `A` for flake8-builtins
# `RUF` for Ruff-specific rules

[lint]
select = ["E", "W", "F", "I", "D", "B", "C4", "A", "RUF"]

ignore = [
  "D100", # Missing docstring in public module
  "D104", # Missing docstring in public package
  "D107", # Missing docstring in __init__
]

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.pydocstyle]
convention = "google"

[lint.isort]
known-first-party = ["pybibx"]

[format]
# Like Black, use double quotes for strings.
quote-style = "double"
# Like Black, indent with spaces, rather than tabs.
indent-style = "space"
# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false
# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
